---
    - name: Setting Ethernet3 description
      eos_interface: name=Ethernet3 description="*** IN USE ***"
            eapi_username={{ eapi_username}} 
            eapi_password={{ eapi_password }} 
            eapi_hostname={{ eapi_hostname }} 
            eapi_port={{ eapi_port }}

    - name: Set Ethernet3 to access mode, VLAN333
      eos_switchport: name=Ethernet3 mode=access access_vlan=333 trunk_allowed_vlans=all
            eapi_username={{ eapi_username}}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}
