---
    - name: Configure Ethernet3 for access mode, VLAN1
      eos_switchport: name=Ethernet3 mode=access access_vlan=1 trunk_allowed_vlans=all
            eapi_username={{ eapi_username }} 
            eapi_password={{ eapi_password }} 
            eapi_hostname={{ eapi_hostname }} 
            eapi_port={{ eapi_port }}

    - name: Reset Ethernet3 description to default
      eos_interface: name=Ethernet3 admin=enable null_as_default=true
            eapi_username={{ eapi_username }}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

    - name: Remove VLANs
      eos_vlan: name={{item.name}} vlanid={{item.vlanid}} state=unconfigured
            eapi_username={{ eapi_username}} 
            eapi_password={{ eapi_password }} 
            eapi_hostname={{ eapi_hostname }} 
            eapi_port={{ eapi_port }}
      with_items:
        - {name: kb1, vlanid: 333}
        - {name: kb2, vlanid: 334}
        - {name: kb3, vlanid: 335}
